# Generated by Django 5.0.3 on 2024-03-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cartproduct_quantity_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='user',
        ),
    ]
